### ISSUE TITLE
Build tooling doesn't appear to be distributing proper module formats

### ISSUE THREAD

**Issue by plwalters** [MarvelousSoftware/marvelous-aurelia-grid#4]
Appears everything is in system.js format.

**Comment by plwalters** [comment]
ex - https://github.com/MarvelousSoftware/marvelous-aurelia-grid/blob/master/dist/amd/grid.js#L1

That `System.register(//...` should be `define(//...`

**Comment by LazerFX** [comment]
This has been causing us issues - we're in a Webpack environment, but no matter what we try, we've been unable to get the grid working; SystemJS errors all over the place.

**Comment by damiankaminski** [comment]
I'll try to fix it over the weekend.

**Comment by LazerFX** [comment]
I've created a pull request to have a start at this myself.  There does appear to be an issue with this - reference the project from webpack, I have to add:

```
resolve: {
    extensions: ['', '.js', '.ts'],
    root: [
       path.resolve('./src')
    ],
   alias: {
       "marvelous-aurelia-core/utils$": "marvelous-aurelia-core/dist/commonjs/utils",
       "marvelous-aurelia-core/aureliaUtils$": "marvelous-aurelia-core/dist/commonjs/aureliaUtils",
       "marvelous-aurelia-core/compiler$": "marvelous-aurelia-core/dist/commonjs/compiler",
       "marvelous-aurelia-core/optionsReader$": "marvelous-aurelia-core/dist/commonjs/optionsReader",
       "marvelous-aurelia-core/pubsub$": "marvelous-aurelia-core/dist/commonjs/pubsub"
   }
},
```

in the webpack.config file.  This is so that it knows to use the right locations...

I've configured the AureliaWebpackPlugin like:

```
new AureliaWebpackPlugin({
    "contextMap": {
        "marvelous-aurelia-grid": "dist/commonjs",
        "marvelous-aurelia-query-language": "dist/commonjs",
        "marvelous-aurelia-core": "dist/commonjs"
    }
}),
```

Unfortunately, this then doesn't load... it's erroring on the (compiled) location, `marvelous-aurelia-grid/dist/commonjs/grid/components/query-language/query-language.js`, line 15 onwards:

```
var QueryLanguageComponent = (function (_super) {
    __extends(QueryLanguageComponent, _super);
    function QueryLanguageComponent(_gridOptions, _gridInternals, _dataSource, _components) {
        _super.call(this);
```

which looks to correspond to the following:

``` TypeScript
constructor(private _gridOptions: GridOptions, private _gridInternals: GridInternals, private _dataSource: DataSource,
  private _components: ComponentsArray) {
    super();
  }
```

This function 'super' I can't find defined anywhere - it's not in `marvelous-aurelia-grid\src\grid\components\query-language`, and it's not in `grid\pluginability` either (which defines GridComponent).  So - a little stuck on where to go on this one.

Hope my investigatory work has started the process off, anyway!

**Comment by damiankaminski** [comment]
"super" is just a base constructor in TypeScript, it is definitely not the problem here. 

Grid project is building properly now, after you PR, but there are other projects (core and query-language) and they are using configuration with exactly same mistake. I'll fix it by the end of tomorrow, but I never used WebPack, so I'm not sure if I will be able to test whether it works properly with it. I may need some help in that regard.

**Comment by plwalters** [comment]
As long as you are outputting the proper module types it should be good

**Comment by damiankaminski** [comment]
@LazerFX I've updated core and query-language projects. Let me know whether it works now.

**Comment by LazerFX** [comment]
Thanks, @damiankaminski - It looks like they're all in the right format now, however I've raised a new issue (#6) that looks to have been exposed.  I think there's differences in the SystemJS/JSPM and WebPack loaders that are being exposed by this project, I'll see if I can resolve it myself, but I've also paged @PWKad on the new issue, see if he's any ideas (Sorry if that's bad form).
